#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'); const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path'); const {spawnSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'); const script=path.join(ROOT,'scripts','build-sec-terminal-wealth-queue-v2.py');
const report=JSON.parse(fs.readFileSync(path.join(ROOT,'reports','early-detection','sec-corporate-action-candidates-2009-2024.json'),'utf8'));
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'sec-tw-queue-')); const output=path.join(temp,'queue.json');
const run=spawnSync(process.env.PYTHON||'python',['-B',script,'--database',report.database,'--output',output],{cwd:ROOT,encoding:'utf8',windowsHide:true});
assert.equal(run.status,0,run.stderr||run.stdout); const summary=JSON.parse(run.stdout); assert.equal(summary.status,'PASS'); assert.equal(summary.rows,44352); assert.equal(summary.outcomesAccessed,false);
const value=JSON.parse(fs.readFileSync(output,'utf8')); assert.deepEqual(value.counts,{rows:44352,form25Family:27285,form15Family:17067,unresolved:44352,resolved:0}); assert.equal(value.inputDatabaseRawSha256,'f6662cf6429a26e55d589712543525840b687dd86ebd973425a8fe5836425ed5'); assert.equal(value.inputEventSequenceSha256,'af54a9caa0e83eb26e985ceaeabff42659ddc3b5b2e22fb3687b560e1c85aedc'); assert.equal(value.claimLocks.outcomesAccessed,false); assert.equal(value.claimLocks.resultComputationAllowed,false); assert.equal(value.rows.every((x,i)=>x.resolutionState==='UNRESOLVED'&&x.outcomesAccessed===false&&x.priorityRank===i+1),true); assert.equal(new Set(value.rows.map(x=>[x.cik,x.accession,x.eventClass,x.filedDate].join('|'))).size,44352);
const second=spawnSync(process.env.PYTHON||'python',['-B',script,'--database',report.database,'--output',output],{cwd:ROOT,encoding:'utf8',windowsHide:true}); assert.notEqual(second.status,0,'overwrite must fail');
const fakeDb=path.join(temp,'fake.sqlite'); fs.copyFileSync(report.database,fakeDb); const mutated=fs.openSync(fakeDb,'r+'); const one=Buffer.alloc(1); fs.readSync(mutated,one,0,1,4096); one[0]^=1; fs.writeSync(mutated,one,0,1,4096); fs.closeSync(mutated); const badOut=path.join(temp,'bad.json'); const tampered=spawnSync(process.env.PYTHON||'python',['-B',script,'--database',fakeDb,'--output',badOut],{cwd:ROOT,encoding:'utf8',windowsHide:true}); assert.notEqual(tampered.status,0,'same-size database mutation must fail'); assert.equal(fs.existsSync(badOut),false);
fs.rmSync(temp,{recursive:true,force:true}); console.log('build-sec-terminal-wealth-queue-v2.test.js: PASS');
