#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'); const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path'); const {spawnSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'); const script=path.join(ROOT,'scripts','build-sec-terminal-wealth-queue-v5.py');
for (const optimization of [[],['-O']]) { const self=spawnSync(process.env.PYTHON||'python',[...optimization,'-B',script,'--self-test'],{cwd:ROOT,encoding:'utf8',windowsHide:true}); assert.equal(self.status,0,self.stderr||self.stdout); const v=JSON.parse(self.stdout); assert.equal(v.status,'PASS'); assert.equal(v.contractRawBound,true); assert.equal(v.samePathSameSizeMutationRejected,true); assert.equal(v.sidecarsFailClosed,true); assert.equal(v.immutableReadOnlyRequired,true); assert.equal(v.privateFullyHashedSnapshotRequired,true); assert.equal(v.nullAndEmptyTickerDistinct,true); assert.equal(v.eventIdAndObservedAtSequenceBound,true); assert.equal(v.outcomesAccessed,false); }
const report=JSON.parse(fs.readFileSync(path.join(ROOT,'reports','early-detection','sec-corporate-action-candidates-2009-2024.json'),'utf8'));
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'sec-tw-v4-')); const output=path.join(temp,'queue.json');
const run=spawnSync(process.env.PYTHON||'python',['-B',script,'--database',report.database,'--output',output],{cwd:ROOT,encoding:'utf8',windowsHide:true}); assert.equal(run.status,0,run.stderr||run.stdout);
const value=JSON.parse(fs.readFileSync(output,'utf8')); assert.equal(value.schema,'early-detection-sec-terminal-wealth-queue/v5'); assert.deepEqual(value.counts,{rows:44352,form25Family:27285,form15Family:17067,unresolved:44352,resolved:0}); assert.equal(value.contractRawSha256,'ea9f1c09a5e2e1536513e53677c941ca8ce737b9d867f330b3052e26515e8124'); assert.equal(value.inputEventSequenceSha256,'e656ab3af95383380c83a9de561b1f39d30b58731cfe824a8f19b72c8b03f40c'); assert.equal(value.rows.every((x,i)=>x.resolutionState==='UNRESOLVED'&&x.outcomesAccessed===false&&x.priorityRank===i+1),true); assert.equal(new Set(value.rows.map(x=>[x.cik,x.accession,x.eventClass,x.filedDate].join('|'))).size,44352);
const second=spawnSync(process.env.PYTHON||'python',['-B',script,'--database',report.database,'--output',output],{cwd:ROOT,encoding:'utf8',windowsHide:true}); assert.notEqual(second.status,0,'overwrite must fail');
fs.rmSync(temp,{recursive:true,force:true}); console.log('build-sec-terminal-wealth-queue-v5.test.js: PASS');
