#!/usr/bin/env node
'use strict';

const assert = require('node:assert/strict');
const test = require('node:test');

require('./helpers/offline-network-guard');
const { fetchOsloUniverse } = require('../discovery/oslo');
assert.ok(
  globalThis[Symbol.for('screener.offlineNetworkGuard')],
  'the process-wide offline guard must be active before the adapter loads',
);

function csv(header, rows) {
  return [
    'European Equities',
    '2026-09-02',
    'Synthetic offline fixture',
    'Generated by oslo-market-ambiguity.test.js',
    header,
    ...rows,
  ].join('\n');
}

async function fetchFixture(payload) {
  let calls = 0;
  const result = await fetchOsloUniverse(async url => {
    calls += 1;
    assert.match(String(url), /mics=XOSL,XOAS,MERK/);
    return payload;
  });
  assert.equal(calls, 1, 'the injected fixture must carry the production fetch path');
  return result;
}

test('Oslo parser accepts only rows with an explicit allowed venue', async t => {
  const header = 'Name;ISIN;Symbol;Market;Currency';

  await t.test('all three documented Oslo venues remain accepted', async () => {
    const result = await fetchFixture(csv(header, [
      'Equinor;NO0000000010;EQNR;Oslo Børs;NOK',
      'Expand;NO0000000028;EXPD;Euronext Expand Oslo;NOK',
      'Growth;NO0000000036;GRWT;Euronext Growth Oslo;NOK',
    ]));
    assert.deepEqual([...result.keys()], ['EQNR.OL', 'EXPD.OL', 'GRWT.OL']);
    assert.equal(result.partial, undefined, 'a healthy register must not be marked partial');
  });

  await t.test('an unknown venue label in every row marks the source partial', async () => {
    const result = await fetchFixture(csv(header, [
      'Drifted A;NO0000000010;EQNR;Oslo Bors Renamed;NOK',
      'Drifted B;NO0000000028;EXPD;Oslo Bors Renamed;NOK',
    ]));
    assert.equal(result.size, 0);
    assert.equal(result.partial, true, 'venue drift must surface as degradation, not as a silent empty source');
  });

  await t.test('a missing Market column marks the source partial', async () => {
    const result = await fetchFixture(csv('Name;ISIN;Symbol;Currency', [
      'Missing market;NO0000000051;MISS;NOK',
    ]));
    assert.equal(result.size, 0);
    assert.equal(result.partial, true);
  });

  await t.test('a foreign venue cannot receive an Oslo ticker', async () => {
    const result = await fetchFixture(csv(header, [
      'Foreign listing;US0000000012;MMM;EuroTLX;EUR',
    ]));
    assert.equal(result.has('MMM.OL'), false);
    assert.equal(result.size, 0);
  });

  await t.test('a blank venue is not silently relabelled Oslo Børs', async () => {
    const result = await fetchFixture(csv(header, [
      'Unknown venue;NO0000000044;BLANK;;NOK',
    ]));
    assert.equal(result.has('BLANK.OL'), false);
    assert.equal(result.size, 0);
  });

  await t.test('a missing Market column invalidates the payload', async () => {
    const result = await fetchFixture(csv('Name;ISIN;Symbol;Currency', [
      'Missing market;NO0000000051;MISS;NOK',
    ]));
    assert.equal(result.has('MISS.OL'), false);
    assert.equal(result.size, 0);
  });
});
