#!/usr/bin/env node
'use strict';

// G4 / Tag 1169: the catch around fetchOsloUniverse returned a bare empty Map,
// so a total Oslo outage reached refresh-universe.js:1609 as "Oslo has zero
// tickers" instead of "Oslo failed". Same shape as edinet-jp.js:157 and
// tsx-ca.js:361, which is what tests/edinet-total-failure-partial.test.js pins.

const assert = require('node:assert/strict');
const test = require('node:test');

require('./helpers/offline-network-guard');
const { fetchOsloUniverse } = require('../discovery/oslo');
assert.ok(
  globalThis[Symbol.for('screener.offlineNetworkGuard')],
  'the process-wide offline guard must be active before the adapter loads',
);

const hasOwn = (value, key) => Object.prototype.hasOwnProperty.call(value, key);

// Header + one accepted venue row; the ASCII venue name keeps this file ASCII-only.
const HEALTHY_CSV = [
  'European Equities',
  '2026-09-02',
  'Synthetic offline fixture',
  'Generated by oslo-catch-partial.test.js',
  'Name;ISIN;Symbol;Market;Currency',
  'Reserve Growth ASA;NO0010000001;RGRW;Euronext Growth Oslo;NOK',
].join('\n');

test('transport failure stays fail-silent but carries an own partial marker', async () => {
  let calls = 0;
  const result = await fetchOsloUniverse(async () => {
    calls += 1;
    throw new Error('synthetic transport failure');
  });

  assert.equal(calls, 1, 'the injected fixture must carry the production fetch path');
  assert.ok(result instanceof Map);
  assert.equal(result.size, 0);
  assert.equal(hasOwn(result, 'partial'), true,
    'a total Oslo outage must be distinguishable from a genuinely empty register');
  assert.equal(result.partial, true);
});

test('healthy pipeline keeps the register unmarked', async () => {
  const result = await fetchOsloUniverse(async () => HEALTHY_CSV);

  assert.ok(result instanceof Map);
  assert.equal(result.size, 1);
  assert.equal(hasOwn(result, 'partial'), false,
    'the success path must not be widened into a blanket partial stamp');
  assert.deepEqual([...result.keys()], ['RGRW.OL']);
});
