#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'); const path=require('node:path'); const os=require('node:os'); const fs=require('node:fs'); const crypto=require('node:crypto'); const {spawnSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'); const script=path.join(ROOT,'scripts','verify-quantconnect-free-cloud-pilot-v2.py');
function run(pyFlags=[],scriptArgs=[]){return spawnSync(process.env.PYTHON||'python',[...pyFlags,'-B',script,...scriptArgs],{cwd:ROOT,encoding:'utf8',windowsHide:true});}
for(const flags of [[],['-O']]){const call=run(flags); assert.equal(call.status,0,call.stderr||call.stdout); const value=JSON.parse(call.stdout); assert.equal(value.status,'PASS'); assert.equal(value.staticContractVerified,true); assert.equal(value.executionBlocked,true); assert.equal(value.outcomesAccessed,false);}
function canonical(value){if(Array.isArray(value))return '['+value.map(canonical).join(',')+']'; if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}'; return JSON.stringify(value);}
function finish(report){const copy=structuredClone(report); delete copy.reportSha256; report.reportSha256=crypto.createHash('sha256').update(canonical(copy)).digest('hex'); return report;}
const cases=JSON.parse(fs.readFileSync(path.join(ROOT,'research','early-detection-v4','quantconnect-free-cloud-pilot-cases-v1.json'),'utf8'));
function output(runId,time){return finish({schema:'early-detection-quantconnect-free-cloud-metadata-output/v2',pilotCoreSha256:'952c509f9eac982ef6f0e6016778a58e0ab1a34bf945fbf2256634cc164dd70a',casesRawSha256:'78be68ce710dedf9e7165c340b733e1ec2ebe6637548d35e704aa20961fbfcd6',providerRunId:runId,executedAt:time,leanVersion:'SYNTHETIC-LOCKED',datasetVersion:'SYNTHETIC-LOCKED',runMode:'DISCOVERY_ONLY',caseCount:50,rows:cases.cases.map(c=>({caseId:c.caseId,category:c.category,querySymbol:c.querySymbol,alternateSymbols:c.alternateSymbols,referenceStart:c.referenceStart,referenceEnd:c.referenceEnd,identityAssessment:'DISCOVERY_ONLY_UNRESOLVED',aliasResults:[c.querySymbol,...c.alternateSymbols].map((s,i)=>({role:i?'ALTERNATE':'PRIMARY',requestedTicker:s,subscriptionAccepted:false,securityIdentifier:null,errors:[]})),barCount:0,firstBarDate:null,lastBarDate:null,splitDates:[],dividendDates:[],symbolChanges:[],delistingEvents:[],errors:[]})),outcomesAccessed:false,priceValuesExported:false,returnsComputed:false,ordersSubmitted:false});}
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'qc-v2-')); const a=path.join(temp,'a.json'),b=path.join(temp,'b.json'); fs.writeFileSync(a,JSON.stringify(output('RUN-A','2026-01-01T00:00:00Z'))+'\n'); fs.writeFileSync(b,JSON.stringify(output('RUN-B','2026-01-01T00:01:00Z'))+'\n');
for(const flags of [[],['-O']]){const call=run(flags,['--run-a',a,'--run-b',b]); assert.equal(call.status,0,call.stderr||call.stdout); assert.equal(JSON.parse(call.stdout).twoRunParityVerified,true);}
const tampered=JSON.parse(fs.readFileSync(a)); tampered.rows[0].price=123; fs.writeFileSync(a,JSON.stringify(finish(tampered))+'\n'); const rejected=run(['-O'],['--run-a',a,'--run-b',b]); assert.notEqual(rejected.status,0,'python -O must not bypass forbidden field validation'); fs.rmSync(temp,{recursive:true,force:true});
console.log('quantconnect-free-cloud-pilot-v2.test.js: PASS');
