#!/usr/bin/env node
/**
 * Tag 134 — Phase 3.6: Methodology Report (monthly summary)
 * =========================================================
 * Eine Datei pro Lauf: outputs/methodology-report.md
 *
 * Verbindet die Outputs von walk-forward-perf und method-effectiveness in einem
 * "entscheidungs-fertigen" Bericht. Beantwortet auf einen Blick:
 *   - Welche Methoden zeigen statistisch signifikantes Alpha (CI lower-bound > 0)?
 *   - Welche Methoden sollten aus den Score-Aggregator-Weights fliegen (CI < 0)?
 *   - Welche brauchen mehr Vintages (insufficient-evidence)?
 *   - Wo steht der Pick-Performance-Audit (vs SPY und vs Frozen-Vintage)?
 *
 * Output ist Markdown so dass Karl ihn direkt in GitHub liest.
 */
'use strict';
const fs = require('fs');
const path = require('path');
// Tag 218: atomic output writes (audit F-218b-03)
const { writeFileAtomic } = require('../lib/atomic-write.js');

const OUT_DIR = path.join(__dirname, '..', 'outputs');
const WALK_FWD = path.join(OUT_DIR, 'walk-forward.json');
const METHOD_EFF = path.join(OUT_DIR, 'method-effectiveness.json');
const OUT_PATH = path.join(OUT_DIR, 'methodology-report.md');

function loadJson(p) { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch (e) { return null; } }

function _fmtAlpha(a) {
  if (a == null || !Number.isFinite(a)) return '—';
  return (a >= 0 ? '+' : '') + a.toFixed(2) + 'pp';
}

function _fmtCi(lo, hi) {
  if (lo == null || hi == null) return '—';
  return `[${lo.toFixed(2)}, ${hi.toFixed(2)}]`;
}

function main() {
  const wf = loadJson(WALK_FWD);
  const me = loadJson(METHOD_EFF);
  if (!wf && !me) {
    console.log('Neither walk-forward.json nor method-effectiveness.json present — exiting.');
    return;
  }
  const today = new Date().toISOString().slice(0, 10);
  let md = '# Methodology Report — ' + today + '\n\n';
  md += '_Generated by `scripts/methodology-report.js`. Combines walk-forward-perf and method-effectiveness._\n\n';

  // ── Section 1: Pick-Performance ────────────────────────────────────
  if (wf && wf.modes) {
    md += '## Pick-Performance (Walk-Forward)\n\n';
    md += '_Vintages analyzed:_ **' + (wf.vintageCount || 0) + '**.\n';
    // Tag 232c-17 (audit F-BT-006 MEDIUM): use canonical medianAlphaVsBenchmark
    // instead of the deprecated medianAlphaVsSpy alias. The benchmark symbol
    // can be SPY / QQQ / IWM depending on which fallback walk-forward-perf
    // chose for the vintage; the "α vs SPY" label was misleading whenever
    // it wasn't actually SPY. Re-label "α vs Benchmark" and surface the
    // actual symbol from the data when available.
    const benchSymbol = (wf.benchmarkSymbol || 'Benchmark');
    md += '_Benchmarks: universe-median (Tag 138: survivor-bias corrected via evaluatedTickers when available) · frozen-vintage-median (no look-ahead survivor selection) · ' + benchSymbol + ' (external)._\n\n';
    for (const [mode, data] of Object.entries(wf.modes)) {
      md += '### ' + mode + '\n\n';
      md += '| Horizon | n vintages | α vs ' + benchSymbol + ' | α vs Frozen-Vintage | α vs Universe | total picks |\n';
      md += '|---|---|---|---|---|---|\n';
      for (const days of (wf.horizonsDays || [7, 28, 84])) {
        const s = data.summary && data.summary[days + 'd'];
        if (!s) continue;
        // Tag 232c-17: prefer medianAlphaVsBenchmark, fall back to medianAlphaVsSpy
        // for older walk-forward.json that predates the rename (compat window).
        const alphaBench = s.medianAlphaVsBenchmark != null ? s.medianAlphaVsBenchmark : s.medianAlphaVsSpy;
        md += `| ${days}d | ${s.vintageCount} | ${_fmtAlpha(alphaBench)} | ${_fmtAlpha(s.medianAlphaVsFrozenVintage)} | ${_fmtAlpha(s.medianAlphaVsUniverse)} | ${s.totalPicks} |\n`;
      }
      md += '\n';
      // Tag 139: regime alpha breakdown
      const hasRegime = (wf.horizonsDays || [7, 28, 84]).some(days => {
        const s = data.summary && data.summary[days + 'd'];
        return s && s.regimeAlpha && Object.keys(s.regimeAlpha).length > 0;
      });
      if (hasRegime) {
        md += '**Regime Alpha (28d, α vs ' + benchSymbol + '):** ';
        const s28 = data.summary && data.summary['28d'];
        if (s28 && s28.regimeAlpha) {
          const parts = ['BULL', 'BEAR', 'SIDEWAYS'].filter(r => s28.regimeAlpha[r]).map(r => {
            const ra = s28.regimeAlpha[r];
            const ab = ra.medianAlphaVsBenchmark != null ? ra.medianAlphaVsBenchmark : ra.medianAlphaVsSpy;
            return `${r} ${_fmtAlpha(ab)} (n=${ra.vintages})`;
          });
          md += parts.join(' · ') + '\n\n';
        } else {
          md += '_no 28d regime data_\n\n';
        }
      }
    }
  } else {
    md += '## Pick-Performance (Walk-Forward)\n\n_walk-forward.json missing — run `node scripts/walk-forward-perf.js` first._\n\n';
  }

  // ── Section 2: Method-Effectiveness Ranking ────────────────────────
  if (me && me.methods) {
    md += '## Method-Effectiveness Ranking (28d horizon)\n\n';
    md += '_alpha = median forward-return of stocks where method passed − median where it failed (pp). 95% CI via 200-resample bootstrap._\n';
    md += '_Methods sorted: significant (CI lower-bound > 0) first; flagged methods (CI upper-bound < 0) last._\n\n';

    const rows28 = Object.entries(me.methods)
      .map(([m, h]) => ({ method: m, d: h['28d'] }))
      .filter(r => r.d);

    const significant = rows28.filter(r => r.d.ciLo95 != null && r.d.ciLo95 > 0);
    const flagged = rows28.filter(r => r.d.ciHi95 != null && r.d.ciHi95 < 0);
    const insufficientEvidence = rows28.filter(r => r.d.evidenceGate !== 'ok');
    const neutral = rows28.filter(r => r.d.evidenceGate === 'ok'
      && !(r.d.ciLo95 != null && r.d.ciLo95 > 0)
      && !(r.d.ciHi95 != null && r.d.ciHi95 < 0));

    md += '### ✅ Significant positive alpha (CI lower-bound > 0) — earn their score weight\n\n';
    if (significant.length === 0) {
      md += '_None yet. Accumulate ≥' + (me.minVintages || 4) + ' vintages of methods-history × prices/history._\n\n';
    } else {
      md += '| Method | alpha | 95% CI | vintages | passN | failN |\n|---|---|---|---|---|---|\n';
      significant.sort((a, b) => b.d.alpha - a.d.alpha);
      for (const r of significant) {
        md += `| ${r.method} | ${_fmtAlpha(r.d.alpha)} | ${_fmtCi(r.d.ciLo95, r.d.ciHi95)} | ${r.d.vintages} | ${r.d.passedN} | ${r.d.failedN} |\n`;
      }
      md += '\n';
    }

    md += '### ⚠ Significant negative alpha (CI upper-bound < 0) — candidates for retirement\n\n';
    if (flagged.length === 0) {
      md += '_None._\n\n';
    } else {
      md += '| Method | alpha | 95% CI | vintages | note |\n|---|---|---|---|---|\n';
      for (const r of flagged) {
        md += `| ${r.method} | ${_fmtAlpha(r.d.alpha)} | ${_fmtCi(r.d.ciLo95, r.d.ciHi95)} | ${r.d.vintages} | review weight in score-aggregator |\n`;
      }
      md += '\n';
    }

    md += '### ◯ Neutral (CI straddles zero) — keep but don\'t over-weight\n\n';
    md += '_' + neutral.length + ' methods. See method-effectiveness.md for full list._\n\n';

    md += '### ▢ Insufficient evidence — not enough vintages or samples yet\n\n';
    md += '_' + insufficientEvidence.length + ' methods. Vintage threshold: ' + (me.minVintages || 4) + '. Sample threshold: ' + (me.minSamplesPerGroup || 10) + ' per group._\n\n';
  } else {
    md += '## Method-Effectiveness\n\n_method-effectiveness.json missing — run `node scripts/method-effectiveness.js` first._\n\n';
  }

  // ── Section 3: Quality-Split sanity check (Phase 3.5) ──────────────
  if (me && me.methods) {
    const anyQualitySplit = Object.values(me.methods).some(h =>
      h['28d'] && h['28d'].byQuality && Object.keys(h['28d'].byQuality).length > 0);
    if (anyQualitySplit) {
      md += '## Method-Effectiveness by Data-Quality Grade (28d)\n\n';
      md += '_If a method\'s alpha is concentrated in A-grade stocks and disappears in B/C, that\'s a finding._\n\n';
      const exemplars = Object.entries(me.methods)
        .filter(([_, h]) => h['28d'] && h['28d'].byQuality && Object.keys(h['28d'].byQuality).length >= 2)
        .slice(0, 12);
      if (exemplars.length === 0) {
        md += '_No methods have data across multiple quality grades yet (Phase 3.4 quality field only recorded since methods-history runs after Tag 134 Phase 3 ship)._\n\n';
      } else {
        md += '| Method | α overall | α A-grade | α B-grade | α C-grade |\n|---|---|---|---|---|\n';
        for (const [methodId, h] of exemplars) {
          const d = h['28d'];
          md += `| ${methodId} | ${_fmtAlpha(d.alpha)} | ${_fmtAlpha(d.byQuality.A && d.byQuality.A.alpha)} | ${_fmtAlpha(d.byQuality.B && d.byQuality.B.alpha)} | ${_fmtAlpha(d.byQuality.C && d.byQuality.C.alpha)} |\n`;
        }
        md += '\n';
      }
    }
  }

  // ── Section 4: Action items ────────────────────────────────────────
  md += '## Action Items\n\n';
  md += '1. Open `outputs/walk-forward.md` for per-vintage detail.\n';
  md += '2. Open `outputs/method-effectiveness.md` for full per-method table.\n';
  md += '3. If any method appears in **flagged** above for ≥3 consecutive monthly reports, propose retirement via ADR-002+ and bump weight to 0 in score-aggregator.\n';
  md += '4. Quality-split section: once Phase 3.4 has ≥4 weeks of `_quality.grade` records, evaluate whether methods should be gated to grade-A stocks only.\n';

  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });
  writeFileAtomic(OUT_PATH, md);
  console.log('Methodology report written: ' + OUT_PATH);
}

if (require.main === module) {
  try { main(); } catch (e) { console.error('methodology-report failed: ' + e.message); process.exit(0); }
}

module.exports = { main };
